import React, { FC } from 'react';
import Head from 'next/head';
import styles from '../layouts/MainLayout.module.css'

import { NavBar } from '../Navbar';
export const MainLayouts : FC = ({ children  }) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Roberto</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <NavBar />
          <main className={styles.main}>
           
            { children }

          </main>
        </div>
      )
}
